apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: predictive-maintenance-server
  annotations:
    scenarios.ai.sap.com/id: "predictive-maintenance"
    scenarios.ai.sap.com/name: "Predictive Maintenance"
    executables.ai.sap.com/id: "serve"
    executables.ai.sap.com/name: "Serve Model"
    executables.ai.sap.com/description: "Real-time failure prediction API"
    artifacts.ai.sap.com/trained-model.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "predictive-maintenance"
    executables.ai.sap.com/id: "serve"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: trained-model
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      annotations: |
        autoscaling.knative.dev/minScale: "1"
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-pj
        containers:
          - name: kserve-container
            image: jpradeep1994/predictive-maintainance:v2.2
            ports:
              - containerPort: 8080
                protocol: TCP
            command: ["python", "serve.py"]
            env:
              - name: MODEL_PATH
                value: /mnt/models
